name: simpsons-paradox
channels:
  - anaconda
  - akode
  - defaults
  - conda-forge
dependencies:
  - ipywidgets=7.5.1
  - jupyterlab=2.2.6
  - matplotlib=3.3.1
  - nodejs=14.9.0
  - numpy=1.19.1
  - pandas=1.1.1
  - python=3.8.5
  - scikit-learn=0.23.2
  - seaborn=0.10.1
  - statsmodels=0.12.0
  - tqdm=4.48.2
  - widgetsnbextension=3.5.1